name = "pc-spa-web"
main = ".open-next/worker.js"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
SITE_URL = "https://getpcspa.com"
ALLOWED_ORIGINS = "https://getpcspa.com,https://pc-spa-web.pc-spa-feedback.workers.dev"
CLOUDFLARE_ENV = "production"
D1_DATABASE_NAME = "pc-spa"

[[d1_databases]]
binding = "DB"
database_name = "pc-spa"
database_id = "ff7e024c-0b2e-462f-83d8-07cc5d41612b"

[[kv_namespaces]]
binding = "PC_SPA_RATE_LIMIT"
id = "f2123aa3d006418483a8d0370168c964"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "pc-spa-web"

[[ratelimits]]
name = "BETA_REQUEST_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 5
period = 60


[env.production]
name = "pc-spa-web"
main = ".open-next/worker.js"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[env.production.assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production.vars]
SITE_URL = "https://getpcspa.com"
ALLOWED_ORIGINS = "https://getpcspa.com,https://pc-spa-web.pc-spa-feedback.workers.dev"
CLOUDFLARE_ENV = "production"
D1_DATABASE_NAME = "pc-spa"

[[env.production.d1_databases]]
binding = "DB"
database_name = "pc-spa"
database_id = "ff7e024c-0b2e-462f-83d8-07cc5d41612b"

[[env.production.kv_namespaces]]
binding = "PC_SPA_RATE_LIMIT"
id = "f2123aa3d006418483a8d0370168c964"

[[env.production.services]]
binding = "WORKER_SELF_REFERENCE"
service = "pc-spa-web"

[[env.production.ratelimits]]
name = "BETA_REQUEST_LIMITER"
namespace_id = "1001"

[env.production.ratelimits.simple]
limit = 5
period = 60
